### ISSUE TITLE
Uncaught TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by lpdx** [Dev-Aryan/web-whatsapp-spam#1]
Occurred running over Chrome 54.0.2840.71 m and WhatsApp 2.16.338.
![capturar](https://cloud.githubusercontent.com/assets/13546280/20107580/23c6b3dc-a5c0-11e6-9358-52fe8b35e221.PNG)

**Comment by Dev-Aryan** [comment]
@lpdx 
This script is now outdated, i am already working on a new script and will upload once done.

Stay Tuned
